apiVersion: v1
kind: Namespace
metadata:
  name: mango

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mango
  namespace: mango
spec:
  serviceName: mango
  replicas: 1
  selector:
    matchLabels:
      app: mango
  template:
    metadata:
      labels:
        app: mango
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
      - name: mango
        image: 566178068807.dkr.ecr.us-west-2.amazonaws.com/mango:v2
        env:
          - name: DATA_DIR
            value: /opt/mango_data
        resources:
          limits:
            memory: "32Mi"
            cpu: "20m"
        ports:
        - containerPort: 6080
        volumeMounts:
        - name: mango
          mountPath: /opt/mango_data
        securityContext:
          allowPrivilegeEscalation: false
  volumeClaimTemplates:
  - metadata:
      name: mango
    spec:
      storageClassName: ebs-sc
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi

---

apiVersion: v1
kind: Service
metadata:
  name: mango
  namespace: mango
spec:
  clusterIP: None
  selector:
    app: mango
  ports:
  - port: 6080
    targetPort: 6080

